### PR TITLE
test #10: add database testing infrastructure; tests and fixes for Base.

### LINKED ISSUE #10: Testing scheme for database calls
Clint writes:

> - Devise a testing scheme for &hellip; database calls that elude straightforward unit testing.
> - Unit test more/all of the surface area we have imported already.

You could also split this into two issues if that's easier&hellip;

### PR DESCRIPTION
**Pull request by clint-tseng**
* the DatabaseShim is the main harness for testing knex’s database
  chaining calls.
  * our Model (Base-derived) objects all use dependency injection to
    actually receive their database objects to work with. What the
    DatabaseShim does is create a mock knex object with all the knex and
    Promise methods mocked out for chaining; but instead of actually
    performing any database actions, they simply record what they were
    called with and move on.
  * the Shim itself provides access to these recorded method calls, and
    a bunch of convenience getters and assertions for pulling out the
    relevant calls and parameters for testing.
* it is a bit of a fine balance between testing the appropriate pieces
  of logic for the database calls and over-testing fairly obvious code,
  but in general expected behaviour should be tested (returning objects
  of the correct type, performing various transformations on the data,
  etc) so that if/as the project grows more complex, our basic contracts
  are not violated.
* closes #10; although more work is needed to expand coverage on extant
  model code.

### CODE REVIEW

File: test/model/package.js [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+const shim = (methodName) => function(...args) {
+  this.__calls.push([ methodName, args ])
+  return this;
+};
+for (const method in knex)
+  if (typeof knex[method] === 'function')
+    knex[method] = shim(method);
+
+// Also, insert Promise methods.
+for (const method of [ 'then' ])
```
Comment (lognaturel) [inline test/model/package.js]: Wow, `for... of`... that's fun!

File: test/model/package.js [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+// expressions easier. But it may grow to include more database testing
+// utilities eventually.
+
+const should = require('should');
+
+// Create a standard knex object, then replace all methods we find with a test
+// harness.
+const knex = require('knex')({ client: 'pg' });
+const shim = (methodName) => function(...args) {
+  this.__calls.push([ methodName, args ])
```
Comment (lognaturel) [inline test/model/package.js]: noob questions -- how exactly is `this` bound here? Why the double underscore?

**Comment by clint-tseng** [comment]
Ha, okay. Three rules about `this` in JS:

First, `this` is bound directly by caller dot notation. So for instance:

    const foo = { bar: function() { console.log(this.baz); }, baz: 42 };
    foo.bar() // prints 42

but,

    const bar2 = foo.bar;
    bar2(); // prints undefined, because this is bound to window instead of foo

and `window` has no `.baz` property. Though in nodejs, it's `global` instead of `window`.

Second, you can bind manually when invoking a function:

    bar2.call(foo); // prints 42
    bar2.apply(foo); // prints 42

You can look up the difference between `call` and `apply` on MDN; they pertain to passed arguments. Though with es6 you should likely use the `...` spread operator instead.

As a corollary to the first two observations, you should be extremely careful with nested functions:

    class A {
      doSomething() {
        this.someMethod(); // works
        this.on('someEvent', function() {
          this.someMethod(); // dangerous! you don't know how this callback is called!
        });
      }
    }

But this is somewhat easily solved (though in my opinion confusingly so) by the third rule, which is that lambda functions _never_ rebind `this`; they are always bound against the closure lexical scope:

    class A {
      doSomething() {
        this.someMethod(); // works
        this.on('someEvent', () => {
          this.someMethod(); // totally safe
        });
      }
    }

**Comment by clint-tseng** [comment]
Oh. And a clarification on "caller dot notation":

    const foo = { bar: { baz: function() { console.log(this.magicNumber); }, magicNumber: 2 }, magicNumber: 1 };
    foo.bar.baz() // prints 2

File: test/model/package.js (hunk 1 above)
Comment (clint-tseng) [reply test/model/package.js]: It is technically still [20% slower](https://jsperf.com/cxlt-iterations) than a pure `for(;;)` loop buuuuut eh? They're tests.

**Comment by lognaturel** [comment]
Thanks for the education. And forgive me for saying that I find it kind of unpleasant. 😅👵🏼

And the `__`? Does it have meaning beyond a single underscore?

File: test/model/base.js [hunk 3]
```diff
@@ -0,0 +1,211 @@
...
+      const [ TestBase, shim ] = DatabaseShim.shim(Base);
+      const TestSubclass = class extends TestBase {
+        paranoia() { return true; }
+      }
+
+      const model = new TestSubclass();
+      model.create();
+
+      const [ promiseCallback ] = shim.paramsForCall('then');
+      promiseCallback.should.be.a.Function;
```
[the remark this answers is not in the document]
Comment (matthew-white) [reply test/model/base.js]: Note: these tests were removed in 7f9dd226fbda4c905e233a404b5afcf60150675f, so we merged this PR without change.
